### ISSUE TITLE
Run failed with NotImplementedError: Unknown device name for getting hardware flops: NVIDIA A100 80GB PCIe

### ISSUE THREAD

**Issue by ggilley** [oumi-ai/oumi#1471]
### What happened?

I started a run on runpod. It failed with the following error:

```
(gpt2-karpathy-pt, pid=2175) [rank0]:     train_step_mfu = calculate_mfu(
(gpt2-karpathy-pt, pid=2175) [rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/oumi/performance/mfu.py", line 182, in calculate_mfu
(gpt2-karpathy-pt, pid=2175) [rank0]:     return calculate_mfu_from_model_flops_per_second(
(gpt2-karpathy-pt, pid=2175) [rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/oumi/performance/mfu.py", line 145, in calculate_mfu_from_model_flops_per_second
(gpt2-karpathy-pt, pid=2175) [rank0]:     device_flops_per_second = _get_device_flops(device_name, dtype) * num_devices
(gpt2-karpathy-pt, pid=2175) [rank0]:   File "/root/miniconda3/lib/python3.10/site-packages/oumi/performance/mfu.py", line 91, in _get_device_flops
(gpt2-karpathy-pt, pid=2175) [rank0]:     raise NotImplementedError(
(gpt2-karpathy-pt, pid=2175) [rank0]: NotImplementedError: Unknown device name for getting hardware flops: NVIDIA A100 80GB PCIe
```

Probably shouldn't be a fatal error (It aborted the run).

### Steps to reproduce the bug

I ran `oumi launch up -c runpod_job.yml`

```
name: gpt2-karpathy-pt

resources:
  cloud: runpod
  accelerators: A100-80GB:1
  use_spot: false
  disk_tier: null

working_dir: .

file_mounts:
  ~/.netrc: ~/.netrc  # WandB credentials

envs:
  WANDB_PROJECT: "oumi testing"
  OUMI_RUN_NAME: gpt2-karpathy.pt

setup: |
  set -e
  pip install uv && uv pip install oumi[gpu]

run: |
  set -e  # Exit if any command failed.
  source ./sky_init.sh

  set -x
  oumi distributed torchrun \
      -m oumi train \
      -c ./train.yml \
      --training.run_name "${OUMI_RUN_NAME}.${SKYPILOT_TASK_ID}" \
      --training.max_steps 100 \
      --training.ddp_find_unused_parameters false \
      --training.dataloader_num_workers 2 \
      --training.dataloader_prefetch_factor 4 \
      --training.enable_wandb true

  echo "Node ${SKYPILOT_NODE_RANK} is all done!"
```

with a train.yml of
```
model:
  model_name: "gpt2" # 124M params
  model_max_length: 1024
  torch_dtype_str: "bfloat16"
  tokenizer_pad_token: "<|endoftext|>"
  attn_implementation: "sdpa"
  load_pretrained_weights: False
  trust_remote_code: True
  model_kwargs:
    disable_dropout: True

data:
  train:
    datasets:
      - dataset_name: "HuggingFaceFW/fineweb-edu"
        subset: "sample-10BT"
        split: "train"
        dataset_kwargs:
          seq_length: 1024
    stream: True
    pack: True
    target_col: "text"

training:
  trainer_type: "TRL_SFT"
  save_steps: 200
  per_device_train_batch_size: 8 # Use 64 for A100-80GB
  gradient_accumulation_steps: 4 # Disable when running on 8 GPUs
  max_steps: 19073

  # If enabled, reduces memory consumption by ~3x but causes a 30% training slowdown.
  enable_gradient_checkpointing: False
  gradient_checkpointing_kwargs:
    use_reentrant: False
  # https://github.com/karpathy/build-nanogpt/blob/master/train_gpt2.py#L349
  optimizer: "adamw_torch_fused"
  learning_rate: 6.0e-04
  lr_scheduler_type: "cosine_with_min_lr"
  lr_scheduler_kwargs:
    min_lr_rate: 0.1
  warmup_steps: 715
  adam_beta1: 0.9
  adam_beta2: 0.95
  weight_decay: 0.1
  compile: True

  run_name: "gpt2-karpathy-pt"
  output_dir: "output/gpt2-karpathy.pt"
  include_performance_metrics: True
```

### System Info

Oumi version: 0.1.6
Python version: 3.10.16
Platform: Linux-6.8.0-52-generic-x86_64-with-glibc2.35

Installed dependencies:
PACKAGE              VERSION
accelerate           1.2.1
aiohttp              3.11.12
bitsandbytes         0.45.2
datasets             3.2.0
diffusers            <not installed>
einops               <not installed>
jsonlines            4.0.0
liger-kernel         0.5.3
llama-cpp-python     <not installed>
lm-eval              0.4.7
numpy                1.26.4
nvidia-ml-py         12.560.30
omegaconf            2.4.0.dev3
open_clip_torch      <not installed>
pandas               2.2.3
peft                 0.14.0
pexpect              4.8.0
pillow               10.3.0
pydantic             2.9.2
responses            0.25.6
skypilot             0.7.0
tensorboard          2.18.0
timm                 <not installed>
torch                2.5.1
torchdata            0.9.0
torchvision          0.20.1
tqdm                 4.67.1
transformers         4.48.3
trl                  0.13.0
typer                0.15.1
vllm                 <not installed>
wandb                0.19.7

Environment variables:
VARIABLE                            VALUE
ACCELERATE_DYNAMO_BACKEND           <not set>
ACCELERATE_DYNAMO_MODE              <not set>
ACCELERATE_DYNAMO_USE_DYNAMIC       <not set>
ACCELERATE_DYNAMO_USE_FULLGRAPH     <not set>
ACCELERATE_USE_FSDP                 <not set>
LOCAL_RANK                          <not set>
LOCAL_WORLD_SIZE                    <not set>
OUMI_EXTRA_DEPS_FILE                <not set>
OUMI_SLURM_CONNECTIONS              <not set>
OUMI_USE_SPOT_VM                    <not set>
RANK                                <not set>
WORLD_SIZE                          <not set>

PyTorch information:
CUDA available: True
CUDA version: 12.4
cuDNN version: 90.1.0
Number of GPUs: 2
GPU type: NVIDIA GeForce RTX 3090
GPU memory: 23.7GB
